# Custom Language File for Launcher Customizer

[ejs.app]
title = "YT Clan"

[ejs.landing]
mediaGitHubURL = "https://github.com/mchlauncher/YT_Clan"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = ""
mediaSoopURL = "#"
mediaChzzkURL = "#"
screenshotsTooltip = "스크린샷"

[ejs.settings]
sourceGithubLink = "https://github.com/mchlauncher/YT_Clan"
supportLink = "https://github.com/mchlauncher/YT_Clan/issues"

[ejs.welcome]
welcomeHeader = "YT Clan"
welcomeDescription = ""
welcomeDescCTA = "[계속] 버튼을 눌러 계속 진행하여 주세요."